version: "3.8"

services:
  # Service Backend 
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    ports:
      - "5000:5000" 
    volumes:
      - ./backend:/app 
      - /app/node_modules 
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/stb_db 
    networks:
      - app-network
    depends_on:
      - mongo 

  # Service Frontend 
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - app-network
    depends_on:
      - backend 

  # Base de données MongoDB 
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db 
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: 
